version: '3.8'
services:
  postgres:
    image: postgres:15.7
    container_name: postgres-dba
    environment:
      POSTGRES_DB: crud-product
      POSTGRES_USER: augusto
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
